// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryMiningRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryMiningRequest) Reset()         { *m = QueryMiningRequest{} }
func (m *QueryMiningRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMiningRequest) ProtoMessage()    {}
func (*QueryMiningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0801432bccbe1b86, []int{0}
}
func (m *QueryMiningRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMiningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMiningRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMiningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMiningRequest.Merge(m, src)
}
func (m *QueryMiningRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMiningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMiningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMiningRequest proto.InternalMessageInfo

func (m *QueryMiningRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryMiningResponse struct {
	TimeLeft int64 `protobuf:"varint,1,opt,name=timeLeft,proto3" json:"timeLeft,omitempty"`
}

func (m *QueryMiningResponse) Reset()         { *m = QueryMiningResponse{} }
func (m *QueryMiningResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMiningResponse) ProtoMessage()    {}
func (*QueryMiningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0801432bccbe1b86, []int{1}
}
func (m *QueryMiningResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMiningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMiningResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMiningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMiningResponse.Merge(m, src)
}
func (m *QueryMiningResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMiningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMiningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMiningResponse proto.InternalMessageInfo

func (m *QueryMiningResponse) GetTimeLeft() int64 {
	if m != nil {
		return m.TimeLeft
	}
	return 0
}

type QueryFaucetRequest struct {
}

func (m *QueryFaucetRequest) Reset()         { *m = QueryFaucetRequest{} }
func (m *QueryFaucetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFaucetRequest) ProtoMessage()    {}
func (*QueryFaucetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0801432bccbe1b86, []int{2}
}
func (m *QueryFaucetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFaucetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFaucetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFaucetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFaucetRequest.Merge(m, src)
}
func (m *QueryFaucetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFaucetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFaucetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFaucetRequest proto.InternalMessageInfo

type QueryFaucetResponse struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *QueryFaucetResponse) Reset()         { *m = QueryFaucetResponse{} }
func (m *QueryFaucetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFaucetResponse) ProtoMessage()    {}
func (*QueryFaucetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0801432bccbe1b86, []int{3}
}
func (m *QueryFaucetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFaucetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFaucetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFaucetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFaucetResponse.Merge(m, src)
}
func (m *QueryFaucetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFaucetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFaucetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFaucetResponse proto.InternalMessageInfo

func (m *QueryFaucetResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryMiningRequest)(nil), "faucet.v1.QueryMiningRequest")
	proto.RegisterType((*QueryMiningResponse)(nil), "faucet.v1.QueryMiningResponse")
	proto.RegisterType((*QueryFaucetRequest)(nil), "faucet.v1.QueryFaucetRequest")
	proto.RegisterType((*QueryFaucetResponse)(nil), "faucet.v1.QueryFaucetResponse")
}

func init() { proto.RegisterFile("v1/query.proto", fileDescriptor_0801432bccbe1b86) }

var fileDescriptor_0801432bccbe1b86 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0xc6, 0x9b, 0xdb, 0x4b, 0xa1, 0x06, 0x21, 0x64, 0x3a, 0xb4, 0x11, 0x44, 0x28, 0x0b, 0x4c,
	0xb1, 0x0a, 0x3b, 0x43, 0x07, 0x26, 0x18, 0xe8, 0x84, 0xba, 0x20, 0x27, 0x3d, 0x49, 0xac, 0x26,
	0x76, 0x6a, 0x3b, 0x45, 0x11, 0x62, 0xe1, 0x09, 0x90, 0x78, 0x29, 0x16, 0xa4, 0x4a, 0x2c, 0x8c,
	0xa8, 0xe5, 0x41, 0x50, 0x13, 0xb7, 0xa2, 0xaa, 0xd8, 0xce, 0x77, 0xfe, 0xfd, 0xce, 0x67, 0xa3,
	0xfd, 0x49, 0x97, 0x8c, 0x73, 0x90, 0x85, 0x97, 0x49, 0xa1, 0x05, 0x6e, 0x86, 0x34, 0x0f, 0x40,
	0x7b, 0x93, 0xae, 0xdd, 0x09, 0x84, 0x4a, 0x85, 0xba, 0x2f, 0x0b, 0xa4, 0x12, 0x55, 0x97, 0x7d,
	0x14, 0x09, 0x11, 0x25, 0x40, 0x68, 0xc6, 0x08, 0xe5, 0x5c, 0x68, 0xaa, 0x99, 0xe0, 0xcb, 0x6a,
	0x2b, 0x12, 0x91, 0xa8, 0xa6, 0x16, 0x91, 0xc9, 0x76, 0xcc, 0x4c, 0xa9, 0xfc, 0x3c, 0x24, 0x94,
	0x1b, 0xa8, 0xeb, 0x21, 0x7c, 0xbb, 0xb8, 0xe1, 0x86, 0x71, 0xc6, 0xa3, 0x3e, 0x8c, 0x73, 0x50,
	0x1a, 0xb7, 0xd1, 0x36, 0x1d, 0x0e, 0x25, 0x28, 0xd5, 0xb6, 0x4e, 0xac, 0xb3, 0x66, 0x7f, 0x29,
	0xdd, 0x2e, 0x3a, 0x5c, 0xeb, 0x57, 0x99, 0xe0, 0x0a, 0xb0, 0x8d, 0x76, 0x34, 0x4b, 0xe1, 0x1a,
	0x42, 0x5d, 0x4e, 0xd4, 0xfb, 0x2b, 0xed, 0xb6, 0x0c, 0xe2, 0xaa, 0xb4, 0x67, 0x10, 0xee, 0xa9,
	0x59, 0xb4, 0xcc, 0x9a, 0x45, 0x07, 0xa8, 0x3e, 0x82, 0xc2, 0x50, 0x17, 0xe1, 0xf9, 0xbb, 0x85,
	0xb6, 0xca, 0x4e, 0x1c, 0xa3, 0xdd, 0x5f, 0x6c, 0x7c, 0xec, 0xad, 0x1e, 0xcc, 0xdb, 0xf4, 0x60,
	0x3b, 0x7f, 0x95, 0x2b, 0x92, 0x6b, 0x3f, 0x7f, 0x7c, 0xbf, 0xfe, 0x6b, 0x61, 0x4c, 0x1e, 0x62,
	0xe0, 0x3d, 0x29, 0xc9, 0xa3, 0x31, 0xf9, 0x84, 0x07, 0x86, 0x54, 0x1d, 0xb7, 0x49, 0x5a, 0xb3,
	0xb2, 0x49, 0x5a, 0xf7, 0xe4, 0xee, 0x95, 0xa4, 0x06, 0xfe, 0x4f, 0x46, 0x50, 0xf4, 0xee, 0xde,
	0x66, 0x8e, 0x35, 0x9d, 0x39, 0xd6, 0xd7, 0xcc, 0xb1, 0x5e, 0xe6, 0x4e, 0x6d, 0x3a, 0x77, 0x6a,
	0x9f, 0x73, 0xa7, 0x36, 0xb8, 0x8c, 0x98, 0x8e, 0x73, 0xdf, 0x0b, 0x44, 0x4a, 0x82, 0x98, 0xca,
	0x04, 0x80, 0x87, 0xc0, 0x48, 0x2a, 0x86, 0x79, 0x02, 0x8a, 0x30, 0x1e, 0xe4, 0x3e, 0xd5, 0x42,
	0x92, 0x8a, 0x47, 0x18, 0xd7, 0x20, 0x39, 0x4d, 0x88, 0x2e, 0x32, 0x50, 0x7e, 0xa3, 0xfc, 0xd2,
	0x8b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xa2, 0x73, 0x1f, 0x59, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Mining queries the faucet module mining
	QueryMining(ctx context.Context, in *QueryMiningRequest, opts ...grpc.CallOption) (*QueryMiningResponse, error)
	// Mint queries the faucet module mint
	QueryFaucet(ctx context.Context, in *QueryFaucetRequest, opts ...grpc.CallOption) (*QueryFaucetResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryMining(ctx context.Context, in *QueryMiningRequest, opts ...grpc.CallOption) (*QueryMiningResponse, error) {
	out := new(QueryMiningResponse)
	err := c.cc.Invoke(ctx, "/faucet.v1.Query/QueryMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryFaucet(ctx context.Context, in *QueryFaucetRequest, opts ...grpc.CallOption) (*QueryFaucetResponse, error) {
	out := new(QueryFaucetResponse)
	err := c.cc.Invoke(ctx, "/faucet.v1.Query/QueryFaucet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Mining queries the faucet module mining
	QueryMining(context.Context, *QueryMiningRequest) (*QueryMiningResponse, error)
	// Mint queries the faucet module mint
	QueryFaucet(context.Context, *QueryFaucetRequest) (*QueryFaucetResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryMining(ctx context.Context, req *QueryMiningRequest) (*QueryMiningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMining not implemented")
}
func (*UnimplementedQueryServer) QueryFaucet(ctx context.Context, req *QueryFaucetRequest) (*QueryFaucetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFaucet not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faucet.v1.Query/QueryMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryMining(ctx, req.(*QueryMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryFaucet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFaucetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryFaucet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faucet.v1.Query/QueryFaucet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryFaucet(ctx, req.(*QueryFaucetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faucet.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryMining",
			Handler:    _Query_QueryMining_Handler,
		},
		{
			MethodName: "QueryFaucet",
			Handler:    _Query_QueryFaucet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/query.proto",
}

func (m *QueryMiningRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMiningRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMiningRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMiningResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMiningResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMiningResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeLeft != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TimeLeft))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryFaucetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFaucetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFaucetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFaucetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFaucetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFaucetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMiningRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMiningResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeLeft != 0 {
		n += 1 + sovQuery(uint64(m.TimeLeft))
	}
	return n
}

func (m *QueryFaucetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFaucetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMiningRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMiningRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMiningRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMiningResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMiningResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMiningResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLeft", wireType)
			}
			m.TimeLeft = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeLeft |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFaucetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFaucetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFaucetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFaucetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFaucetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFaucetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
